#!/bin/bash
# ==============================================================================
# Setup Passwordless Sudo for PostgreSQL Operations
# ==============================================================================
# This script configures /etc/sudoers.d/ to allow the current user to run
# PostgreSQL management commands without entering a password.
#
# Usage: sudo bash setup_passwordless_postgres.sh
# ==============================================================================

set -e

# Get the username (the user who will run map_pro)
if [ -n "$SUDO_USER" ]; then
    TARGET_USER="$SUDO_USER"
else
    TARGET_USER="$(whoami)"
fi

if [ "$TARGET_USER" = "root" ]; then
    echo "Error: Do not run this as root user directly."
    echo "Usage: sudo bash setup_passwordless_postgres.sh"
    exit 1
fi

echo "Configuring passwordless sudo for user: $TARGET_USER"

# Create sudoers.d file for map_pro PostgreSQL operations
SUDOERS_FILE="/etc/sudoers.d/map_pro_postgres"

cat > "$SUDOERS_FILE" << EOF
# Map Pro PostgreSQL Management - Passwordless Sudo
# Generated by setup_passwordless_postgres.sh
#
# Allows $TARGET_USER to manage PostgreSQL without password prompts

# System service management
$TARGET_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl start postgresql
$TARGET_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop postgresql
$TARGET_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart postgresql
$TARGET_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl status postgresql
$TARGET_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl is-active postgresql

# PostgreSQL commands as postgres user
$TARGET_USER ALL=(postgres) NOPASSWD: /usr/bin/initdb
$TARGET_USER ALL=(postgres) NOPASSWD: /usr/bin/psql
$TARGET_USER ALL=(postgres) NOPASSWD: /usr/bin/createuser
$TARGET_USER ALL=(postgres) NOPASSWD: /usr/bin/createdb
$TARGET_USER ALL=(postgres) NOPASSWD: /usr/bin/dropdb
$TARGET_USER ALL=(postgres) NOPASSWD: /usr/bin/dropuser
$TARGET_USER ALL=(postgres) NOPASSWD: /usr/bin/pg_ctl
$TARGET_USER ALL=(postgres) NOPASSWD: /usr/bin/cat
$TARGET_USER ALL=(postgres) NOPASSWD: /usr/bin/test
$TARGET_USER ALL=(postgres) NOPASSWD: /bin/sh

# File ownership for PostgreSQL data directory
$TARGET_USER ALL=(ALL) NOPASSWD: /usr/bin/chown -R postgres\:postgres /mnt/map_pro/database/postgres*
$TARGET_USER ALL=(ALL) NOPASSWD: /usr/bin/mkdir -p /mnt/map_pro/database/postgres*
EOF

# Set correct permissions (required for sudoers.d files)
chmod 0440 "$SUDOERS_FILE"

# Validate the sudoers file
if visudo -c -f "$SUDOERS_FILE"; then
    echo ""
    echo "SUCCESS: Passwordless sudo configured for PostgreSQL operations."
    echo ""
    echo "The following commands will no longer require a password:"
    echo "  - sudo systemctl start/stop/restart postgresql"
    echo "  - sudo -u postgres initdb ..."
    echo "  - sudo -u postgres psql ..."
    echo "  - sudo -u postgres createuser/createdb ..."
    echo "  - sudo chown for PostgreSQL directories"
    echo ""
    echo "You can now run 'python main.py' without password prompts."
else
    echo "ERROR: Invalid sudoers syntax. Removing file."
    rm -f "$SUDOERS_FILE"
    exit 1
fi
