# Path: verification/engine/checks/core/__init__.py
"""
Core building blocks for verification checks.

Contains:
- CheckResult: Standardized result dataclass
- constants: Check names and tolerance values
- check_constants: Additional configuration constants
- decimal_tolerance: XBRL decimal tolerance comparison
- value_parsing: Value parsing utilities
- concept_normalization: Concept name normalization
"""

from .check_result import CheckResult
from .constants import (
    # Horizontal checks
    CHECK_CALCULATION_CONSISTENCY,
    CHECK_TOTAL_RECONCILIATION,
    CHECK_SIGN_CONVENTION,
    CHECK_DUPLICATE_FACTS,
    HORIZONTAL_CHECK_NAMES,
    # Vertical checks
    CHECK_COMMON_VALUES_CONSISTENCY,
    VERTICAL_CHECK_NAMES,
    # Library checks
    CHECK_CONCEPT_VALIDITY,
    CHECK_PERIOD_TYPE_MATCH,
    CHECK_BALANCE_TYPE_MATCH,
    CHECK_DATA_TYPE_MATCH,
    LIBRARY_CHECK_NAMES,
    # Tolerances
    DEFAULT_CALCULATION_TOLERANCE,
    DEFAULT_ROUNDING_TOLERANCE,
    LARGE_VALUE_THRESHOLD,
    CALCULATION_COMPLETENESS_THRESHOLD,
    OVERSHOOT_ROUNDING_THRESHOLD,
    # Concept normalization
    CONCEPT_SEPARATORS,
    CANONICAL_SEPARATOR,
    ConceptNormalizer,
    # Dimensional context detection
    DIMENSIONAL_CONTEXT_INDICATORS,
    # Period extraction patterns
    PERIOD_TYPE_INDICATORS,
    CONTEXT_ID_DATE_SEPARATORS,
    DATE_COMPONENT_PATTERNS,
    PERIOD_EXTRACTION_PATTERNS,
)
from .check_constants import (
    SIGN_MAGNITUDE_TOLERANCE,
    SIGN_DOUBLING_TOLERANCE,
    DECIMAL_COMPARISON_EPSILON_BASE,
    DECIMAL_EPSILON_MULTIPLIER,
    CALC_VERIFIER_DEFAULT_TOLERANCE,
    CALC_VERIFIER_DEFAULT_ROUNDING,
    INITIAL_EXPECTED_SUM,
    DEFAULT_OVERSHOOT_RATIO,
    MAX_MISSING_CHILDREN_DISPLAY,
    FIRST_ELEMENT_INDEX,
    SAMPLE_CONCEPTS_LIMIT,
    SAMPLE_CONTEXTS_LIMIT,
    DUPLICATE_PERCENTAGE_TOLERANCE,
    MAX_EXTENSION_PREFIX_LENGTH,
    NIL_VALUE_RETURN,
    VERTICAL_DEFAULT_VALUE,
    CONTEXT_COUNT_MINIMUM,
    MAX_INCONSISTENT_DUPLICATES_DISPLAY,
    MAX_MULTI_ROLE_PARENTS_LOG,
    MAX_DUPLICATES_DISPLAY,
    INITIAL_EXPECTED_SUM_HORIZONTAL,
    DEFAULT_OVERSHOOT_RATIO_HORIZONTAL,
    MAX_MISSING_CHILDREN_DISPLAY_HORIZONTAL,
    ZERO_VALUE_HORIZONTAL,
    ZERO_THRESHOLD,
    MIN_DUPLICATE_ENTRIES,
    ITERATION_START_INDEX,
    REGEX_YEAR_PATTERN,
    REGEX_FLAGS_VALUE,
    PERIOD_TYPE_DURATION,
    PERIOD_TYPE_INSTANT,
    PERIOD_TYPE_UNKNOWN,
    MATCH_TYPE_EXACT,
    MATCH_TYPE_FALLBACK,
    MATCH_TYPE_PERIOD_MATCH,
    MATCH_TYPE_NONE,
)
from .decimal_tolerance import DecimalTolerance, ToleranceResult
from .value_parsing import ValueParser, NIL_VALUES, EM_DASH, EN_DASH
from .concept_normalization import (
    ConceptNormalizer as ConceptNormalizerNew,
    KNOWN_TAXONOMY_PREFIXES,
    MAX_EXTENSION_PREFIX_LENGTH as MAX_EXT_PREFIX_LEN,
)

__all__ = [
    # Check result
    'CheckResult',
    # Constants - horizontal
    'CHECK_CALCULATION_CONSISTENCY',
    'CHECK_TOTAL_RECONCILIATION',
    'CHECK_SIGN_CONVENTION',
    'CHECK_DUPLICATE_FACTS',
    'HORIZONTAL_CHECK_NAMES',
    # Constants - vertical
    'CHECK_COMMON_VALUES_CONSISTENCY',
    'VERTICAL_CHECK_NAMES',
    # Constants - library
    'CHECK_CONCEPT_VALIDITY',
    'CHECK_PERIOD_TYPE_MATCH',
    'CHECK_BALANCE_TYPE_MATCH',
    'CHECK_DATA_TYPE_MATCH',
    'LIBRARY_CHECK_NAMES',
    # Constants - tolerances
    'DEFAULT_CALCULATION_TOLERANCE',
    'DEFAULT_ROUNDING_TOLERANCE',
    'LARGE_VALUE_THRESHOLD',
    'CALCULATION_COMPLETENESS_THRESHOLD',
    'OVERSHOOT_ROUNDING_THRESHOLD',
    # Concept normalization
    'CONCEPT_SEPARATORS',
    'CANONICAL_SEPARATOR',
    'ConceptNormalizer',
    'ConceptNormalizerNew',
    'KNOWN_TAXONOMY_PREFIXES',
    # Dimensional context
    'DIMENSIONAL_CONTEXT_INDICATORS',
    # Period extraction
    'PERIOD_TYPE_INDICATORS',
    'CONTEXT_ID_DATE_SEPARATORS',
    'DATE_COMPONENT_PATTERNS',
    'PERIOD_EXTRACTION_PATTERNS',
    # Decimal tolerance
    'DecimalTolerance',
    'ToleranceResult',
    # Value parsing
    'ValueParser',
    'NIL_VALUES',
    'EM_DASH',
    'EN_DASH',
    # Check constants
    'SIGN_MAGNITUDE_TOLERANCE',
    'SIGN_DOUBLING_TOLERANCE',
    'DECIMAL_COMPARISON_EPSILON_BASE',
    'DECIMAL_EPSILON_MULTIPLIER',
    'CALC_VERIFIER_DEFAULT_TOLERANCE',
    'CALC_VERIFIER_DEFAULT_ROUNDING',
    'INITIAL_EXPECTED_SUM',
    'DEFAULT_OVERSHOOT_RATIO',
    'MAX_MISSING_CHILDREN_DISPLAY',
    'FIRST_ELEMENT_INDEX',
    'SAMPLE_CONCEPTS_LIMIT',
    'SAMPLE_CONTEXTS_LIMIT',
    'DUPLICATE_PERCENTAGE_TOLERANCE',
    'MAX_EXTENSION_PREFIX_LENGTH',
    'NIL_VALUE_RETURN',
    'VERTICAL_DEFAULT_VALUE',
    'CONTEXT_COUNT_MINIMUM',
    'MAX_INCONSISTENT_DUPLICATES_DISPLAY',
    'MAX_MULTI_ROLE_PARENTS_LOG',
    'MAX_DUPLICATES_DISPLAY',
    'INITIAL_EXPECTED_SUM_HORIZONTAL',
    'DEFAULT_OVERSHOOT_RATIO_HORIZONTAL',
    'MAX_MISSING_CHILDREN_DISPLAY_HORIZONTAL',
    'ZERO_VALUE_HORIZONTAL',
    'ZERO_THRESHOLD',
    'MIN_DUPLICATE_ENTRIES',
    'ITERATION_START_INDEX',
    'REGEX_YEAR_PATTERN',
    'REGEX_FLAGS_VALUE',
    'PERIOD_TYPE_DURATION',
    'PERIOD_TYPE_INSTANT',
    'PERIOD_TYPE_UNKNOWN',
    'MATCH_TYPE_EXACT',
    'MATCH_TYPE_FALLBACK',
    'MATCH_TYPE_PERIOD_MATCH',
    'MATCH_TYPE_NONE',
]
